name: CI

on:
  push:
    branches: [main, 'renovate/**']
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: ${{ env.NODE_VERSION }}
      env:
        NODE_VERSION: 18.16.0 # renovate: datasource=node depName=node
    - name: Cache Yarn packages
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: Run tests
      run: yarn test
