name: CI

on:
  push:
    branches: [main, 'renovate/**']
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: ${{ env.NODE_VERSION }}
      env:
        NODE_VERSION: 18.14.1 # renovate: datasource=node depName=node
    - name: Cache Yarn packages
      uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3.2.6
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: Run tests
      run: yarn test
