---
# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
name: Cleanup workflow cache

'on':
  pull_request:
    types: [closed]
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00
  workflow_dispatch:

permissions: {}

jobs:
  cleanup:
    name: Cleanup cache
    permissions:
      actions: write
    runs-on: ubuntu-latest
    env:
      BRANCH: >-
        ${{
          github.event_name == 'pull_request' && github.event.pull_request.merged && format('refs/pull/{0}/merge', github.event.pull_request.number)
          || github.event_name != 'pull_request' && github.ref
          || ''
        }}
    steps:
      - if: env.BRANCH != ''
        name: Cleanup stale cache entries on ${{ env.BRANCH }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          # Get cache keys that don't include the branch's SHA (if not a PR)
          gh actions-cache list -R ${{ github.repository }} -B $BRANCH --order asc --sort last-used | cut -f 1 > cache-keys.txt
          [ -z "${{ github.event.pull_request }}" ] && grep -v ${{ github.sha }} cache-keys.txt > cache-keys.txt.tmp && mv cache-keys.txt.tmp cache-keys.txt
          CACHE_KEYS="$(cat cache-keys.txt | tr '\n' ' ')"
          for key in $CACHE_KEYS; do
            gh actions-cache delete $key -R ${{ github.repository }} -B $BRANCH --confirm
          done
