# Update markdown files and assets used in my GitHub profile
name: Update GitHub Profile

'on':
  pull_request:
    paths:
      - '.github/workflows/update-profile.yaml'
      - 'templates/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/update-profile.yaml'
      - 'templates/**'
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Get Wokrflow Application Token
        id: get-workflow-app-token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          permissions: 'contents:write, pull_requests:write'

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.get-workflow-app-token.outputs.token }}

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          cache: yarn
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 18.16.1 # renovate: datasource=node depName=node

      - name: Install dependencies
        run: yarn install --immutable

      - uses: muesli/readme-scribe@d2f6ab32d6b9f5b59941fe782d6c7e6499a37fe4
        env:
          GITHUB_TOKEN: ${{ secrets.README_SCRIBE_GH_TOKEN }}
        with:
          template: 'templates/README.tpl.md'
          writeTo: 'README.md'

      - name: Lint and fix
        run: yarn lint:fix

      # Commit changes to the branch when triggered from a pull request
      - name: Commit changes to HEAD
        uses: EndBug/add-and-commit@v9.1.3
        if: github.event_name == 'pull_request'
        with:
          author_name: 'mrbro-bot[bot]'
          author_email: '137683033+mrbro-bot[bot]@users.noreply.github.com'
          committer_name: 'MrBro Bot'
          committer_email: '137683033+mrbro-bot[bot]@users.noreply.github.com'
          message: 'build: update README.md'

      # Create a pull request when triggered from a push, schedule, or workflow_dispatch event
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5.0.2
        if: github.ref == 'refs/heads/main'
        with:
          assignees: 'marcusrbrown'
          author: 'mrbro-bot[bot] <137683033+mrbro-bot[bot]@users.noreply.github.com>'
          body: |
            This is an automated pull request to update the README.md file and assets used in my GitHub profile.
            Please review the changes and merge this pull request if you approve.

            > _This pull request was automatically created by [create-pull-request][1]._

            [1]: https://github.com/peter-evans/create-pull-request 'Create Pull Request action on GitHub'
          branch: 'build/update-readme'
          commit-message: 'build: update README.md'
          committer: 'MrBro Bot <137683033+mrbro-bot[bot]@users.noreply.github.com>'
          title: 'build: update README.md'
          token: ${{ steps.get-workflow-app-token.outputs.token }}
