---
# Update markdown files and assets used in my GitHub profile
name: Update GitHub Profile

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prepare:
    if: github.event_name == 'pull_request'
    name: Prepare
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ github.head_ref }}

      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            changes:
              - '.github/workflows/update-profile.yaml'
              - 'templates/**'
              - 'scripts/fetch-sponsors-data.ts'
              - 'scripts/update-sponsors.ts'
              - 'scripts/update-badges.ts'
              - 'types/sponsors.ts'
              - 'types/badges.ts'
              - 'utils/github-api.ts'
              - 'utils/badge-*.ts'

  finalize:
    # Run this job even when the markscribe job is skipped
    if: github.event_name != 'pull_request' || needs.prepare.outputs.changes == 'true'
    name: Finalize
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - id: get-workflow-app-token
        name: Get Workflow Application Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          private-key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.get-workflow-app-token.outputs.token }}

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Fetch sponsor data
        run: pnpm sponsors:fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SPONSORS_TOKEN }}
        continue-on-error: true

      - name: Update SPONSORME.md from template
        run: pnpm sponsors:update
        continue-on-error: true

      - name: Fetch badge data
        run: pnpm badges:fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SPONSORS_TOKEN }}
        continue-on-error: true

      - name: Update BADGES.md from template
        run: pnpm badges:update
        continue-on-error: true

      - name: Update README
        uses: muesli/readme-scribe@d2f6ab32d6b9f5b59941fe782d6c7e6499a37fe4
        env:
          GITHUB_TOKEN: ${{ secrets.README_SCRIBE_GH_TOKEN }}
        with:
          template: templates/README.tpl.md
          writeTo: README.md

      - name: Fix linting errors
        run: pnpm fix

      # Commit changes to the branch when triggered from a pull request
      - name: Commit changes to HEAD
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        if: github.event_name == 'pull_request'
        with:
          author_name: 'mrbro-bot[bot]'
          author_email: '137683033+mrbro-bot[bot]@users.noreply.github.com'
          committer_name: 'mrbro-bot[bot]'
          committer_email: '137683033+mrbro-bot[bot]@users.noreply.github.com'
          message: 'build: update generated profile content'

      # Create a pull request when triggered from a push, schedule, or workflow_dispatch event
      - name: Create pull request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        if: github.ref == 'refs/heads/main'
        with:
          assignees: marcusrbrown
          author: 'mrbro-bot[bot] <137683033+mrbro-bot[bot]@users.noreply.github.com>'
          body: |
            This is an automated pull request to update generated profile content and assets used in my GitHub profile.
            Please review the changes and merge this pull request if you approve.

            <sup>
            _This pull request was automatically created by [create-pull-request][1] ([#${{ github.run_number }}][2])._
            </sup>

            [1]: https://github.com/peter-evans/create-pull-request 'Create Pull Request action on GitHub'
            [2]: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} 'Workflow run on GitHub'
          branch: build/update-readme
          commit-message: 'build: update generated profile content'
          committer: 'mrbro-bot[bot] <137683033+mrbro-bot[bot]@users.noreply.github.com>'
          sign-commits: true
          title: 'build: update generated profile content'
          token: ${{ steps.get-workflow-app-token.outputs.token }}
